## Configuration file

name: Un Podcast Trans
url: https://1pct.fr

author: Niléane Dorffer
description: On bavarde, on se redécouvre, et puis on est trans ✨
title: Un Podcast Trans

permalink: /:year/:month/:day/:title.html
markdown: kramdown

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
